### ISSUE TITLE
Use React in production mode

### ISSUE THREAD

**Issue by RickWong** [monkberry/benchmark#1]
Turn off debugging and dev warnings by setting `process.env.NODE_ENV` to `production`. It will make React much faster in the benchmarks.

**Comment by antonmedv** [comment]
I build benchmarks with webpack, does `process.env.NODE_ENV` affect in browsers?

**Comment by RickWong** [comment]
Yes. Because require("react") is used, it's necessary to set the env.

**Comment by skaag** [comment]
I'd love to see new benchmarks after this is fixed.

**Comment by pedroborges** [comment]
I updated the benchmark to use the latest version of monkberry, include Vue.js and used `PRODUCTION` for the `NODE_ENV`.

## Single point rendering Run benchmark

### Chrome 51
- **Monkberry** 522 141 op/sec ±19.23% (34 runs sampled)
- React 226 op/sec ±15.51% (26 runs sampled)
- Vue 58 203 op/sec ±14.92% (33 runs sampled)
- Template string 358 op/sec ±17.84% (41 runs sampled)

### Safari 9
- **Monkberry** 826 260 op/sec ±6.62% (51 runs sampled)
- React 144 op/sec ±17.55% (37 runs sampled)
- Vue 82 898 op/sec ±12.92% (36 runs sampled)
- Template string 314 op/sec ±8.01% (42 runs sampled)

## First rendering Run benchmark

Benchmark compare first time rendering of complex template. It shows how quickly the user can see an interface. For html markup was used real template of airline ticket and real data of representing tickets.

### Chrome 51
- Monkberry 247 op/sec ±18.39% (28 runs sampled)
- React 92.88 op/sec ±27.94% (32 runs sampled)
- **Vue** 4 897 op/sec ±28.65% (25 runs sampled)
- Template string 187 op/sec ±20.68% (23 runs sampled)

### Safari 9
- Monkberry 668 op/sec ±11.93% (48 runs sampled)
- React 219 op/sec ±18.77% (49 runs sampled)
- **Vue** 18 777 op/sec ±36.40% (34 runs sampled)
- Template string 403 op/sec ±24.22% (40 runs sampled)

## Repeated rendering Run benchmark

This benchmark is same as the previous, but it does not rerender entire template, it's updates data of template with update and setState methods.

### Chrome 51
- Monkberry 1 197 op/sec ±18.07% (34 runs sampled)
- React 192 op/sec ±50.42% (37 runs sampled)
- **Vue** 71 079 op/sec ±13.74% (49 runs sampled)
- Template string 350 op/sec ±9.01% (44 runs sampled)

### Safari 9
- Monkberry 2 277 op/sec ±15.82% (47 runs sampled)
- React 115 op/sec ±19.03% (32 runs sampled)
- **Vue** 31 992 op/sec ±13.17% (40 runs sampled)
- Template string 353 op/sec ±10.29% (43 runs sampled)

## Todos rendering Run benchmark

In this benchmark compare rendering of todo list (11 items) with random data. Using update and setState methods.

### Chrome 51
- **Monkberry** 14 311 op/sec ±23.00% (7 runs sampled)
- React 1 633 op/sec ±28.15% (8 runs sampled)
- Vue 6 790 op/sec ±30.59% (8 runs sampled)
- Template string 11 356 op/sec ±8.65% (9 runs sampled)

### Safari 9
- **Monkberry** 11 748 op/sec ±8.75% (45 runs sampled)
- React 1 155 op/sec ±21.68% (38 runs sampled)
- Vue 6 828 op/sec ±9.76% (35 runs sampled)
- Template string 6 962 op/sec ±3.81% (51 runs sampled)

**Comment by elfet** [comment]
@pedroborges hi, will publish react prod soon, but it looks line you implementation of vue bench isn't correct.

**Comment by antonmedv** [comment]
I updated all packages and build all benchmarks again with `process.env.NODE_ENV` == `production`.
Now React looks better, but still it's some times SLOWER than innerHTML by 10%. 

And still Monkberry is fastest :) Some times [significant faster](http://monkberry.js.org/benchmark/single-point-rendering.html).

![monkberry benchmarks](https://cloud.githubusercontent.com/assets/141232/16612623/0de49466-4392-11e6-90d2-fd8598543287.png)
